# ============================================================
# EMYRS - AzMove Migration Script Template
# ============================================================
# This script is generated by Emyrs tool. 
# Run this on SAW machine after taking JIT access.
# ============================================================

# ==================== CONFIGURATION ====================
# These values are filled by Emyrs based on your deployment and Kusto queries
# 
# KUSTO QUERY TO GET THESE VALUES:
# ─────────────────────────────────────────────────────────────
# cluster('azcore.centralus.kusto.windows.net').database('AzureCP').
# MycroftContainerSnapshot_Latest
# | where VirtualMachineUniqueId == "<VM_UNIQUE_ID>"
# | project Cluster, TenantName, ClusterName
# ─────────────────────────────────────────────────────────────

# Region: <REGION> (useast2euap or uscentraleuap)
# Scenario: <SCENARIO>

# Subscription where resources are created
$crpSubscriptionId = "<SUBSCRIPTION_ID>"

# TenantName from Kusto query (MycroftContainerSnapshot_Latest.TenantName)
# Example: "20499ca6-ab49-46ff-968e-7aedddcbd95e"
$tenantName = "<TENANT_NAME>"

# FabricId = ClusterName from Kusto query (MycroftContainerSnapshot_Latest.ClusterName)
# Example: "CDM06PrdApp17"
$fabricId = "<FABRIC_ID>"

# ==================== GET AZMOVE ENDPOINT ====================
# Use the "Cluster" value from Kusto query directly!
# Example: "uscentraleuap-prod-b" or "useast2euap-prod-b"

$AzMove = Get-AzMove -Name <AZMOVE_ENDPOINT>

# ==================== CREATE MIGRATION INPUT ====================

$migrationInput = New-AzMoveObject AzMove.Controller.MigrateRunningTenantToMerlinInput

# Dynamic values (from Kusto)
$migrationInput | Update-AzMoveObject -PropertyName FabricId -PropertyValue $fabricId
$migrationInput | Update-AzMoveObject -PropertyName NrpSubscriptionId -PropertyValue $crpSubscriptionId

# Fixed values (always the same)
$migrationInput | Update-AzMoveObject -PropertyName RegionalNetworkResourceChannelType -PropertyValue "ViaPubSub"
$migrationInput | Update-AzMoveObject -PropertyName VipGoalStateChannelType -PropertyValue "ViaPubSub"
$migrationInput | Update-AzMoveObject -PropertyName RollbackMode -PropertyValue "Optimized"

# ==================== STEP 1: VALIDATE ====================
# Always run validation first!

Write-Host "Running Validation API..." -ForegroundColor Yellow
$validateResult = ($AzMove | Invoke-AzMoveApi -MethodName AzMoveService_ValidateMigrateRunningTenantToMerlinAsyncByCrpsubscriptionidTenantnameMigrationinputAsync -Parameters @($crpSubscriptionId, $tenantName, $migrationInput)).Result

Write-Host "Validation Result:" -ForegroundColor Cyan
$validateResult

# ==================== STEP 2: MIGRATE ====================
# Only run this AFTER validation succeeds!
# Uncomment the lines below when ready to migrate

# Write-Host "Running Migration API..." -ForegroundColor Yellow
# $migrateResult = ($AzMove | Invoke-AzMoveApi -MethodName AzMoveService_MigrateRunningTenantToMerlinAsyncByCrpsubscriptionidTenantnameMigrationinputAsync -Parameters @($crpSubscriptionId, $tenantName, $migrationInput)).Result

# Write-Host "Migration Result:" -ForegroundColor Cyan
# $migrateResult

# ==================== NOTES ====================
# After running the APIs, go back to Emyrs and say:
# "I ran the validation API" or "I ran both APIs"
# Emyrs will then check AzMoveDiagnostics for the results
